MASTER_TEMPLATE = {
    "Balance Sheet": [
        ("", "Particulars", "Note", "header_col"),
        ("I", "EQUITY AND LIABILITIES", None, "header"),
        ("1", "Shareholder's funds", None, "sub_header"),
        ("(a)", "Share Capital", "1", "item"),
        ("(b)", "Reserves and surplus", "2", "item"),
        ("2", "Non-current liabilities", None, "sub_header"),
        ("(a)", "Long-term borrowings", "3", "item"),
        ("(b)", "Deferred tax liabilities (Net)", "4", "item"),
        ("(c)", "Other Long-term liabilities", "5", "item"),
        ("(d)", "Long-term provisions", "6", "item"),
        ("3", "Current liabilities", None, "sub_header"),
        ("(a)", "Short-term borrowings", "7", "item"),
        ("(b)", "Trade payables", "8", "item"),
        ("(c)", "Other current liabilities", "9", "item"),
        ("(d)", "Short-term provisions", "10", "item"),
        ("", "TOTAL EQUITY AND LIABILITIES", ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], "total"),
        ("", "", None, "spacer"),
        ("II", "ASSETS", None, "header"),
        ("1", "Non-current assets", None, "sub_header"),
        ("(a)", "Fixed assets (Tangible & Intangible)", "11", "item"),
        ("(b)", "Non-current investments", "12", "item"),
        ("(c)", "Deferred tax assets (Net)", "4", "item"),
        ("(d)", "Long-term loans and advances", "13", "item"),
        ("(e)", "Other non-current assets", "14", "item"),
        ("2", "Current assets", None, "sub_header"),
        ("(a)", "Current investments", "15", "item"),
        ("(b)", "Inventories", "16", "item"),
        ("(c)", "Trade receivables", "17", "item"),
        ("(d)", "Cash and cash equivalents", "18", "item"),
        ("(e)", "Short-term loans and advances", "19", "item"),
        ("(f)", "Other current assets", "20", "item"),
        ("", "TOTAL ASSETS", ["11", "12", "4", "13", "14", "15", "16", "17", "18", "19", "20"], "total"),
    ],
    "Profit and Loss": [
        ("", "Particulars", "Note", "header_col"),
        ("I", "Revenue from operations", "21", "item"),
        ("II", "Other Income", "22", "item"),
        ("III", "Total Revenue (I + II)", ["21", "22"], "total"),
        ("", "", None, "spacer"),
        ("IV", "Expenses", None, "header"),
        ("", "Cost of Materials Consumed", "23", "item_no_alpha"),
        ("", "Changes in inventories", "16", "item_no_alpha"),
        ("", "Employee benefit expenses", "24", "item_no_alpha"),
        ("", "Finance Costs", "25", "item_no_alpha"),
        ("", "Depreciation and amortization expenses", "11", "item_no_alpha"),
        ("", "Other expenses", "26", "item_no_alpha"),
        ("","Total Expenses", ["23", "16", "24", "25", "11", "26"], "total"),
        ("", "", None, "spacer"),
        ("V", "Profit before tax (III - IV)", "PBT", "total"),
        ("", "", None, "spacer"),
        ("VI", "Tax expense", None, "header"),
        ("", "Current tax", "27", "item_no_alpha"),
        ("", "Deferred tax", "4", "item_no_alpha"),
        ("","Total Tax Expense", ["27", "4"], "total"),
        ("", "", None, "spacer"),
        ("VII", "Profit/(Loss) for the period (V - VI)", "PAT", "total"),
    ],
    "Notes to Accounts": NOTES_STRUCTURE_AND_MAPPING
}
